#!/bin/bash
BRANCH_NAME=`git rev-parse --abbrev-ref @`;
DERIVERD_BRANCH_NAME=`git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -1 | awk -F'[]~^[]' '{print $2}'`

DIFF_BASE_BRANCH_NAME=""
if [[ `echo $DERIVERD_BRANCH_NAME` ]] ; then
  DIFF_BASE_BRANCH_NAME=$DERIVERD_BRANCH_NAME
elif [[ `echo $BRANCH_NAME | grep 'feature'` ]] ; then
  DIFF_BASE_BRANCH_NAME="develop"
else
  DIFF_BASE_BRANCH_NAME="master"
fi

git diff origin/$DIFF_BASE_BRANCH_NAME... -U0 --no-color | perl -ne '
  if (/^diff --git a\/(\S+)/) { $f = $1; }
  if (/^\@\@ -\d+(?:,\d+)? \+(\d+)/) {
    print "$f:$1\n"; $f = "";
  }
'